--COUNT TOTAL USERS IN EACH MARKET
WITH ALL_USERS AS (
SELECT CASE WHEN COUNTRY = 'Argentina' THEN 'AR'
            WHEN COUNTRY = 'Brazil' THEN 'BR' 
            WHEN COUNTRY = 'Colombia' THEN 'CO'
            WHEN COUNTRY = 'Dominican Republic' THEN 'DO'
            WHEN COUNTRY = 'Ecuador' THEN 'EC'
            WHEN COUNTRY = 'Mexico' THEN 'MX'
            WHEN COUNTRY = 'Panama' THEN 'PA'
            WHEN COUNTRY = 'Peru' THEN 'PE'
            WHEN COUNTRY = 'Paraguay' THEN 'PY'
            WHEN COUNTRY = 'El Salvador' THEN 'SV'
            WHEN COUNTRY = 'Uruguay' THEN 'UY'
            WHEN COUNTRY = 'South Africa' THEN 'ZA'
            ELSE NULL END AS COUNTRY,
  DATE_TRUNC('MONTH', DAY) AS MONTH,
  COUNT(DISTINCT USER_ID) AS TOTAL_USERS
FROM WH.ANALYTICS.T_GLOBAL_ACTIVE_USERS
WHERE COUNTRY IN ('Argentina', 'Brazil', 'Colombia', 'Dominican Republic',
                 'Ecuador', 'Mexico', 'Panama', 'Peru', 'Paraguay', 'El Salvador',
                 'Uruguay', 'South Africa')
GROUP BY COUNTRY,
  MONTH
),
RAW_USERS_WITH_EMAIL AS (
SELECT DISTINCT 'BR' AS COUNTRY,
    USER_ID,
    EMAIL,
    DATE_TRUNC('MONTH', RECEIVED_AT) AS MONTH
FROM SEGMENT_EVENTS.BR_PARCEIRO_ANDROID.IDENTIFIES
WHERE EMAIL IS NOT NULL 
AND RECEIVED_AT >= '2021-09-01'
UNION ALL
SELECT DISTINCT 'BR' AS COUNTRY,
    USER_ID,
    EMAIL,
    DATE_TRUNC('MONTH', RECEIVED_AT) AS MONTH
FROM SEGMENT_EVENTS.BR_PARCEIRO_IOS.IDENTIFIES
WHERE EMAIL IS NOT NULL 
AND RECEIVED_AT >= '2021-09-01'
UNION ALL
SELECT DISTINCT 'BR' AS COUNTRY,
    USER_ID,
    EMAIL,
    DATE_TRUNC('MONTH', RECEIVED_AT) AS MONTH
FROM SEGMENT_EVENTS.BR_PARCEIRO_WEB.IDENTIFIES
WHERE EMAIL IS NOT NULL 
AND RECEIVED_AT >= '2021-09-01'
  
UNION ALL
SELECT DISTINCT 'CO' AS COUNTRY,
    USER_ID,
    EMAIL,
    DATE_TRUNC('MONTH', RECEIVED_AT) AS MONTH
FROM SEGMENT_EVENTS.CO_BAVARIA_ANDROID_PROD.IDENTIFIES
WHERE EMAIL IS NOT NULL 
AND RECEIVED_AT >= '2021-09-01'
UNION ALL
SELECT DISTINCT 'CO' AS COUNTRY,
    USER_ID,
    EMAIL,
    DATE_TRUNC('MONTH', RECEIVED_AT) AS MONTH
FROM SEGMENT_EVENTS.CO_BAVARIA_IOS_PROD.IDENTIFIES
WHERE EMAIL IS NOT NULL 
AND RECEIVED_AT >= '2021-09-01'
UNION ALL
SELECT DISTINCT 'CO' AS COUNTRY,
    USER_ID,
    EMAIL,
    DATE_TRUNC('MONTH', RECEIVED_AT) AS MONTH
FROM SEGMENT_EVENTS.CO_BAVARIA_WEB_PROD.IDENTIFIES
WHERE EMAIL IS NOT NULL 
AND RECEIVED_AT >= '2021-09-01'
  
UNION ALL
SELECT DISTINCT 'CO' AS COUNTRY,
    USER_ID,
    EMAIL,
    DATE_TRUNC('MONTH', RECEIVED_AT) AS MONTH
FROM SEGMENT_EVENTS.DR_MI_CERVECERIA_ANDROID.IDENTIFIES
WHERE EMAIL IS NOT NULL 
AND RECEIVED_AT >= '2021-09-01'
UNION ALL
SELECT DISTINCT 'CO' AS COUNTRY,
    USER_ID,
    EMAIL,
    DATE_TRUNC('MONTH', RECEIVED_AT) AS MONTH
FROM SEGMENT_EVENTS.DR_MI_CERVECERIA_IOS.IDENTIFIES
WHERE EMAIL IS NOT NULL 
AND RECEIVED_AT >= '2021-09-01'
UNION ALL
SELECT DISTINCT 'CO' AS COUNTRY,
    USER_ID,
    EMAIL,
    DATE_TRUNC('MONTH', RECEIVED_AT) AS MONTH
FROM SEGMENT_EVENTS.DR_MI_CERVECERIA_WEB.IDENTIFIES
WHERE EMAIL IS NOT NULL 
AND RECEIVED_AT >= '2021-09-01'
),
USERS_WITH_EMAIL AS (
SELECT COUNTRY,
  MONTH,
  COUNT(DISTINCT USER_ID) AS USERS_WITH_EMAIL
FROM RAW_USERS_WITH_EMAIL
GROUP BY COUNTRY,
  MONTH
),
USERS_RECEIVED_EMAIL AS (
SELECT COUNTRY,
  COUNT(DISTINCT USER_ID) AS USERS_SENT_EMAIL,
  DATE_TRUNC('MONTH', RECEIVED_AT) AS MONTH
FROM WH.DM_DIGITAL_COMMS.TRACKS_GLOBAL_EMAILS
WHERE EVENT = 'email_sent'
GROUP BY COUNTRY,
  MONTH
)
SELECT A.COUNTRY,
    A.MONTH,
    TOTAL_USERS,
    USERS_WITH_EMAIL,
    USERS_SENT_EMAIL
FROM ALL_USERS A
JOIN USERS_WITH_EMAIL W
    ON A.COUNTRY = W.COUNTRY
    AND A.MONTH = W.MONTH
JOIN USERS_RECEIVED_EMAIL R
    ON A.COUNTRY = R.COUNTRY
    AND A.MONTH = R.MONTH
