SELECT COUNTRY,
    CAMPAIGN_ID,
    CHANNEL,
    DATE_TRUNC('DAY', IMPRESSION_TIME) AS DAY_MESSAGE_SENT,
    'Flec' AS CONVERSION_TYPE,
    COUNT(DISTINCT POC_ID) AS POCS_CONVERTED,
    COUNT(DISTINCT USER_ID) AS USERS_CONVERTED,
    COUNT(DISTINCT SEND_ID) AS CONVERSIONS
FROM {{ ref('background_flex_conversions' )}} 
GROUP BY COUNTRY,
    CAMPAIGN_ID,
    CHANNEL,
    DAY_MESSAGE_SENT
