SELECT COUNTRY,
    CAMPAIGN_ID,
    CHANNEL,
    'Marketplace' AS CONVERSION_TYPE,
    COUNT(DISTINCT POC_ID) AS POCS_CONVERTED,
    COUNT(DISTINCT USER_ID) AS USERS_CONVERTED,
    COUNT(DISTINCT SEND_ID) AS CONVERSIONS
FROM {{ ref('background_marketplace_conversions' )}} 
GROUP BY COUNTRY,
    CAMPAIGN_ID,
    CHANNEL
