--This table contains marketplace conversions using product added as the event where the conversion event is within 1 days of the impression
-- A marketplace conversion is defined as an product added event where the SKU is a marketplace SKU
