--This table contains sales brand conversions using order completed as the event where the conversion event is within 1 days of the impression
-- A sales brand conversion is defined as an order completed event where the Brand matches the Brand tagged in the campaign
