--This table contains sales sku conversions using order completed as the event where the conversion event is within 7 days of the impression
-- A sales sku conversion is defined as an order completed event where the SKU matches the SKU tagged in the campaign
