WITH IMP AS (
SELECT COUNTRY,
  POC_ID,
  DAY,
  PUSH_IMPRESSIONS,
  IN_APP_IMPRESSIONS,
  IN_APP_SALES_IMPRESSIONS,
  PUSH_SALES_IMPRESSIONS,
  SALES_IMPRESSIONS,
  IN_APP_ALGO_IMPRESSIONS,
  PUSH_ALGO_IMPRESSIONS,
  ALGO_IMPRESSIONS,
  IN_APP_REWARDS_PHOTO_IMPRESSIONS,
  PUSH_REWARDS_PHOTO_IMPRESSIONS,
  REWARDS_PHOTO_IMPRESSIONS,
  IN_APP_REWARDS_PURCHASE_IMPRESSIONS,
  PUSH_REWARDS_PURCHASE_IMPRESSIONS,
  REWARDS_REDEMPTION_IMPRESSIONS,
  ORDER_VIS_IMPRESSIONS,
  IN_APP_ORDER_VIS_IMPRESSIONS,
  PUSH_ORDER_VIS_IMPRESSIONS,
  TOTAL_IMPRESSIONS,
  TOTAL_IMPRESSIONS - ORDER_VIS_IMPRESSIONS AS COMMERCIAL_IMPRESSIONS,
  PUSH_IMPRESSIONS - PUSH_ORDER_VIS_IMPRESSIONS AS COMMERCIAL_PUSH_IMPRESSIONS,
  IN_APP_IMPRESSIONS - IN_APP_ORDER_VIS_IMPRESSIONS AS COMMERCIAL_IN_APP_IMPRESSIONS
FROM {{ ref('poc_daily_impressions' )}}
),

CLICKS AS (
SELECT COUNTRY,
  POC_ID,
  DAY,
  PUSH_CLICKS,
  IN_APP_CLICKS,
  IN_APP_SALES_CLICKS,
  PUSH_SALES_CLICKS,
  SALES_CLICKS,
  IN_APP_ALGO_CLICKS,
  PUSH_ALGO_CLICKS,
  ALGO_CLICKS,
  IN_APP_REWARDS_PHOTO_CLICKS,
  PUSH_REWARDS_PHOTO_CLICKS,
  REWARDS_PHOTO_CLICKS,
  IN_APP_REWARDS_PURCHASE_CLICKS,
  PUSH_REWARDS_PURCHASE_CLICKS,
  REWARDS_PURCHASE_CLICKS,
  IN_APP_REWARDS_REDEMPTION_CLICKS,
  PUSH_REWARDS_REDEMPTION_CLICKS,
  REWARDS_REDEMPTION_CLICKS,
  ORDER_VIS_CLICKS,
  IN_APP_ORDER_VIS_CLICKS,
  PUSH_ORDER_VIS_CLICKS,
  TOTAL_CLICKS,
  TOTAL_CLICKS - ORDER_VIS_CLICKS AS COMMERCIAL_CLICKS,
  PUSH_CLICKS - PUSH_ORDER_VIS_CLICKS AS COMMERCIAL_PUSH_CLICKS,
  IN_APP_CLICKS - IN_APP_ORDER_VIS_CLICKS AS COMMERCIAL_IN_APP_CLICKS
FROM {{ ref('poc_daily_clicks' )}}
),

PUSH_TTC AS (
SELECT COUNTRY,
  POC_ID,
  DAY,
  AVG_PUSH_SECONDS_TO_CLICK
FROM {{ ref('user_daily_time_to_click_push' )}}
),

IN_APP_TTC AS (
SELECT COUNTRY,
  POC_ID,
  DAY,
  AVG_IN_APP_SECONDS_TO_CLICK
FROM {{ ref('user_daily_time_to_click_in_app' )}}
),

ALGO_CONV AS (
SELECT COUNTRY,
  POC_ID,
  DAY,
  SUM(CASE WHEN CHANNEL = 'PUSH' THEN ALGO_CONVERSIONS ELSE 0 END) AS PUSH_ALGO_CONVERSIONS,
  SUM(CASE WHEN CHANNEL = 'IN-APP' THEN ALGO_CONVERSIONS ELSE 0 END) AS IN_APP_ALGO_CONVERSIONS
FROM {{ ref('user_daily_conversion_algo' )}}
GROUP BY COUNTRY,
  USER_ID,
  DAY
),

PHOTO_CONV AS (
SELECT COUNTRY,
  POC_ID,
  DAY,
  SUM(CASE WHEN CHANNEL = 'PUSH' THEN PHOTO_CHALLENGE_CONVERSIONS ELSE 0 END) AS PUSH_PHOTO_CONVERSIONS,
  SUM(CASE WHEN CHANNEL = 'IN-APP' THEN PHOTO_CHALLENGE_CONVERSIONS ELSE 0 END) AS IN_APP_PHOTO_CONVERSIONS
FROM {{ ref('user_daily_conversion_photo_challenge' )}}
GROUP BY COUNTRY,
  USER_ID,
  DAY
),

PURCHASE_CONV AS (
SELECT COUNTRY,
  POC_ID,
  DAY,
  SUM(CASE WHEN CHANNEL = 'PUSH' THEN PURCHASE_CHALLENGE_CONVERSIONS ELSE 0 END) AS PUSH_PURCHASE_CONVERSIONS,
  SUM(CASE WHEN CHANNEL = 'IN-APP' THEN PURCHASE_CHALLENGE_CONVERSIONS ELSE 0 END) AS IN_APP_PURCHASE_CONVERSIONS
FROM {{ ref('user_daily_conversion_purchase_challenge' )}}
GROUP BY COUNTRY,
  USER_ID,
  DAY
),

REDEMPTION_CONV AS (
SELECT COUNTRY,
  POC_ID,
  DAY,
  SUM(CASE WHEN CHANNEL = 'PUSH' THEN REDEMPTION_CONVERSIONS ELSE 0 END) AS PUSH_REDEMPTION_CONVERSIONS,
  SUM(CASE WHEN CHANNEL = 'IN-APP' THEN REDEMPTION_CONVERSIONS ELSE 0 END) AS IN_APP_REDEMPTION_CONVERSIONS
FROM {{ ref('user_daily_conversion_redemption' )}}
GROUP BY COUNTRY,
  USER_ID,
  DAY
),

SALES_CONV AS (
SELECT COUNTRY,
  POC_ID,
  DAY,
  SUM(CASE WHEN CHANNEL = 'PUSH' THEN SALES_CONVERSIONS ELSE 0 END) AS PUSH_SALES_CONVERSIONS,
  SUM(CASE WHEN CHANNEL = 'IN-APP' THEN SALES_CONVERSIONS ELSE 0 END) AS IN_APP_SALES_CONVERSIONS
FROM {{ ref('user_daily_conversion_sales' )}}
GROUP BY COUNTRY,
  USER_ID,
  DAY
)

SELECT I.COUNTRY,
  I.POC_ID,
  I.DAY,
  PUSH_IMPRESSIONS,
  IN_APP_IMPRESSIONS,
  IN_APP_SALES_IMPRESSIONS,
  PUSH_SALES_IMPRESSIONS,
  SALES_IMPRESSIONS,
  IN_APP_ALGO_IMPRESSIONS,
  PUSH_ALGO_IMPRESSIONS,
  ALGO_IMPRESSIONS,
  IN_APP_REWARDS_PHOTO_IMPRESSIONS,
  PUSH_REWARDS_PHOTO_IMPRESSIONS,
  REWARDS_PHOTO_IMPRESSIONS,
  IN_APP_REWARDS_PURCHASE_IMPRESSIONS,
  PUSH_REWARDS_PURCHASE_IMPRESSIONS,
  REWARDS_REDEMPTION_IMPRESSIONS,
  ORDER_VIS_IMPRESSIONS,
  IN_APP_ORDER_VIS_IMPRESSIONS,
  PUSH_ORDER_VIS_IMPRESSIONS,
  TOTAL_IMPRESSIONS,
  COMMERCIAL_IMPRESSIONS,
  COMMERCIAL_PUSH_IMPRESSIONS,
  COMMERCIAL_IN_APP_IMPRESSIONS,
  IFNULL(PUSH_CLICKS, 0) AS PUSH_CLICKS,
  IFNULL(IN_APP_CLICKS, 0) AS IN_APP_CLICKS,
  IFNULL(IN_APP_SALES_CLICKS, 0) AS IN_APP_SALES_CLICKS,
  IFNULL(PUSH_SALES_CLICKS, 0) AS PUSH_SALES_CLICKS,
  IFNULL(SALES_CLICKS, 0) AS SALES_CLICKS,
  IFNULL(IN_APP_ALGO_CLICKS, 0) AS IN_APP_ALGO_CLICKS,
  IFNULL(PUSH_ALGO_CLICKS, 0) AS PUSH_ALGO_CLICKS,
  IFNULL(ALGO_CLICKS, 0) AS ALGO_CLICKS,
  IFNULL(IN_APP_REWARDS_PHOTO_CLICKS, 0) AS IN_APP_REWARDS_PHOTO_CLICKS,
  IFNULL(PUSH_REWARDS_PHOTO_CLICKS, 0) AS PUSH_REWARDS_PHOTO_CLICKS,
  IFNULL(REWARDS_PHOTO_CLICKS, 0) AS REWARDS_PHOTO_CLICKS,
  IFNULL(IN_APP_REWARDS_PURCHASE_CLICKS, 0) AS IN_APP_REWARDS_PURCHASE_CLICKS,
  IFNULL(PUSH_REWARDS_PURCHASE_CLICKS, 0) AS PUSH_REWARDS_PURCHASE_CLICKS,
  IFNULL(REWARDS_PURCHASE_CLICKS, 0) AS REWARDS_PURCHASE_CLICKS,
  IFNULL(IN_APP_REWARDS_REDEMPTION_CLICKS, 0) AS IN_APP_REWARDS_REDEMPTION_CLICKS,
  IFNULL(PUSH_REWARDS_REDEMPTION_CLICKS, 0) AS PUSH_REWARDS_REDEMPTION_CLICKS,
  IFNULL(REWARDS_REDEMPTION_CLICKS, 0) AS REWARDS_REDEMPTION_CLICKS,
  IFNULL(ORDER_VIS_CLICKS, 0) AS ORDER_VIS_CLICKS,
  IFNULL(IN_APP_ORDER_VIS_CLICKS, 0) AS IN_APP_ORDER_VIS_CLICKS,
  IFNULL(PUSH_ORDER_VIS_CLICKS, 0) AS PUSH_ORDER_VIS_CLICKS,
  IFNULL(TOTAL_CLICKS, 0) AS TOTAL_CLICKS,
  IFNULL(TOTAL_CLICKS, 0) - IFNULL(ORDER_VIS_CLICKS, 0) AS COMMERCIAL_CLICKS,
  IFNULL(PUSH_CLICKS, 0) - IFNULL(PUSH_ORDER_VIS_CLICKS, 0) AS COMMERCIAL_PUSH_CLICKS,
  IFNULL(IN_APP_CLICKS, 0) - IFNULL(IN_APP_ORDER_VIS_CLICKS, 0) AS COMMERCIAL_IN_APP_CLICKS,
  IFNULL(AVG_PUSH_SECONDS_TO_CLICK, 0) AS AVG_PUSH_SECONDS_TO_CLICK,
  IFNULL(AVG_IN_APP_SECONDS_TO_CLICK, 0) AS AVG_IN_APP_SECONDS_TO_CLICK,
  IFNULL(PUSH_ALGO_CONVERSIONS, 0) AS PUSH_ALGO_CONVERSIONS,
  IFNULL(IN_APP_ALGO_CONVERSIONS, 0) AS IN_APP_ALGO_CONVERSIONS,
  IFNULL(PUSH_PHOTO_CONVERSIONS, 0) AS PUSH_PHOTO_CONVERSIONS,
  IFNULL(IN_APP_PHOTO_CONVERSIONS, 0) AS IN_APP_PHOTO_CONVERSIONS,
  IFNULL(PUSH_PURCHASE_CONVERSIONS, 0) AS PUSH_PURCHASE_CONVERSIONS,
  IFNULL(IN_APP_PURCHASE_CONVERSIONS, 0) AS IN_APP_PURCHASE_CONVERSIONS,
  IFNULL(PUSH_REDEMPTION_CONVERSIONS, 0) AS PUSH_REDEMPTION_CONVERSIONS,
  IFNULL(IN_APP_REDEMPTION_CONVERSIONS, 0) AS IN_APP_REDEMPTION_CONVERSIONS,
  IFNULL(PUSH_SALES_CONVERSIONS, 0) AS PUSH_SALES_CONVERSIONS,
  IFNULL(IN_APP_SALES_CONVERSIONS, 0) AS IN_APP_SALES_CONVERSIONS
FROM IMP I
LEFT JOIN CLICKS C
    ON I.COUNTRY = C.COUNTRY
    AND I.POC_ID = C.POC_ID
    AND I.DAY = C.DAY
LEFT JOIN PUSH_TTC PT
    ON I.COUNTRY = PT.COUNTRY
    AND I.POC_ID = PT.POC_ID
    AND I.DAY = PT.DAY
LEFT JOIN IN_APP_TTC IAT
    ON I.COUNTRY = IAT.COUNTRY
    AND I.POC_ID = IAT.POC_ID
    AND I.DAY = IAT.DAY
LEFT JOIN ALGO_CONV AC
    ON I.COUNTRY = AC.COUNTRY
    AND I.POC_ID = AC.POC_ID
    AND I.DAY = AC.DAY
LEFT JOIN PHOTO_CONV PHOC
    ON I.COUNTRY = PHOC.COUNTRY
    AND I.POC_ID = PHOC.POC_ID
    AND I.DAY = PHOC.DAY
LEFT JOIN PURCHASE_CONV PURC
    ON I.COUNTRY = PURC.COUNTRY
    AND I.POC_ID = PURC.POC_ID
    AND I.DAY = PURC.DAY
LEFT JOIN REDEMPTION_CONV REDC
    ON I.COUNTRY = REDC.COUNTRY
    AND I.POC_ID = REDC.POC_ID
    AND I.DAY = REDC.DAY
LEFT JOIN SALES_CONV SC
    ON I.COUNTRY = SC.COUNTRY
    AND I.POC_ID = SC.POC_ID
    AND I.DAY = SC.DAY
