-- This table contains a list of click events and their corresponding impression event

WITH 
  

SENDS AS (
SELECT COUNTRY,
    CAMPAIGN_ID,
    CHANNEL,
    USER_ID,
    ID AS SEND_ID,
    RECEIVED_AT AS SEND_TIME
FROM {{ ref('tracks_global_messages' )}}
WHERE EVENT IN ('in_app_message_viewed', 'push_notification_sent')
),

CLICKS AS (
SELECT COUNTRY,
    CAMPAIGN_ID,
    CHANNEL,
    USER_ID,
    ID AS CLICK_ID,
    RECEIVED_AT AS CLICK_TIME
FROM {{ ref('tracks_global_messages' )}}
WHERE EVENT IN ('in_app_message_clicked', 'push_notification_tapped')
),

COMBINED AS (
SELECT S.COUNTRY,
    S.CAMPAIGN_ID,
    S.CHANNEL,
    S.USER_ID,
    SEND_ID,
    CLICK_ID,
    SEND_TIME,
    CLICK_TIME,
    DATEDIFF(SECOND, SEND_TIME, CLICK_TIME) AS SECONDS_DIFF
FROM SENDS S
JOIN CLICKS C
    ON S.COUNTRY = C.COUNTRY
    AND S.CAMPAIGN_ID = C.CAMPAIGN_ID
    AND S.CHANNEL = C.CHANNEL
    AND S.USER_ID = C.USER_ID
--Filter to events where the date diff is between 0 and 7 days
WHERE SECONDS_DIFF BETWEEN 0 AND 604800
  AND S.CHANNEL = 'PUSH'

UNION ALL
SELECT S.COUNTRY,
    S.CAMPAIGN_ID,
    S.CHANNEL,
    S.USER_ID,
    SEND_ID,
    CLICK_ID,
    SEND_TIME,
    CLICK_TIME,
    DATEDIFF(SECOND, SEND_TIME, CLICK_TIME) AS SECONDS_DIFF
FROM SENDS S
JOIN CLICKS C
    ON S.COUNTRY = C.COUNTRY
    AND S.CAMPAIGN_ID = C.CAMPAIGN_ID
    AND S.CHANNEL = C.CHANNEL
    AND S.USER_ID = C.USER_ID
--Filter to events where the date diff is between 0 and 1 hour
WHERE SECONDS_DIFF BETWEEN 0 AND 900
  AND S.CHANNEL = 'IN-APP'
),

QUALIFIED AS (
SELECT COUNTRY,
    CAMPAIGN_ID,
    CHANNEL,
    USER_ID,
    SEND_ID,
    CLICK_ID,
    SEND_TIME,
    CLICK_TIME,
    SECONDS_DIFF
FROM COMBINED
QUALIFY ROW_NUMBER() OVER(PARTITION BY SEND_ID ORDER BY SECONDS_DIFF) = 1
AND ROW_NUMBER() OVER(PARTITION BY CLICK_ID ORDER BY SECONDS_DIFF) = 1
) 

SELECT *, DATEDIFF(SECOND, SEND_TIME, CLICK_TIME) AS TIMEDIFF, CURRENT_TIMESTAMP AS UPDATED_AT
FROM QUALIFIED
