-- Should update incrementally - not currently part of production
-- Pulling in data from WH.SEGMENT DIM tables based off of the product array in SEGMENT_EVENTS.XX.ORDER_COMPLETED

SELECT 'AR' AS COUNTRY, 
    ORDER_ITEM_ID, 
    ORDER_ID, 
    POC_ID, 
    RECEIVED_AT, 
    PRODUCT_BRAND, 
    PRODUCT_QUANTITY, 
    PRODUCT_REVENUE, 
    PRODUCT_SKU, 
    PRODUCT_NAME, 
    PRODUCT_RECOMMENDATION_TYPE 
FROM WH.segment.dim_ar_order_items --WH.SEGMENT.DIM_AR_ORDER_ITEMS 

UNION ALL   
SELECT 'BR' AS COUNTRY, 
ORDER_ITEM_ID, 
    ORDER_ID, 
    POC_ID, 
    RECEIVED_AT, 
    PRODUCT_BRAND, 
    PRODUCT_QUANTITY, 
    PRODUCT_REVENUE, 
    PRODUCT_SKU, 
    PRODUCT_NAME, 
    PRODUCT_RECOMMENDATION_TYPE 
FROM WH.segment.dim_br_order_items --WH.SEGMENT.DIM_BR_ORDER_ITEMS 

UNION ALL   
SELECT 'CO' AS COUNTRY, 
ORDER_ITEM_ID, 
    ORDER_ID, 
    POC_ID, 
    RECEIVED_AT, 
    PRODUCT_BRAND, 
    PRODUCT_QUANTITY, 
    PRODUCT_REVENUE, 
    PRODUCT_SKU, 
    PRODUCT_NAME, 
    PRODUCT_RECOMMENDATION_TYPE 
FROM WH.segment.dim_co_order_items --WH.SEGMENT.DIM_CO_ORDER_ITEMS 

UNION ALL   
SELECT 'DO' AS COUNTRY, 
    ORDER_ITEM_ID, 
    ORDER_ID, 
    POC_ID, 
    RECEIVED_AT, 
    PRODUCT_BRAND, 
    PRODUCT_QUANTITY, 
    PRODUCT_REVENUE, 
    PRODUCT_SKU, 
    PRODUCT_NAME, 
    PRODUCT_RECOMMENDATION_TYPE 
FROM WH.segment.dim_do_order_items --WH.SEGMENT.DIM_DO_ORDER_ITEMS 

UNION ALL   

SELECT 'EC' AS COUNTRY, 
    ORDER_ITEM_ID, 
    ORDER_ID, 
    POC_ID, 
    RECEIVED_AT, 
    PRODUCT_BRAND, 
    PRODUCT_QUANTITY, 
    PRODUCT_REVENUE, 
    PRODUCT_SKU, 
    PRODUCT_NAME, 
    PRODUCT_RECOMMENDATION_TYPE 
FROM WH.segment.dim_ec_order_items --WH.SEGMENT.DIM_EC_ORDER_ITEMS 

UNION ALL   
SELECT 'MX' AS COUNTRY, 
    ORDER_ITEM_ID, 
    ORDER_ID, 
    POC_ID, 
    RECEIVED_AT, 
    PRODUCT_BRAND, 
    PRODUCT_QUANTITY, 
    PRODUCT_REVENUE, 
    PRODUCT_SKU, 
    PRODUCT_NAME, 
    PRODUCT_RECOMMENDATION_TYPE 
FROM WH.segment.dim_mx_order_items --WH.SEGMENT.DIM_MX_ORDER_ITEMS 

UNION ALL   
SELECT 'PA' AS COUNTRY, 
    ORDER_ITEM_ID, 
    ORDER_ID, 
    POC_ID, 
    RECEIVED_AT, 
    PRODUCT_BRAND, 
    PRODUCT_QUANTITY, 
    PRODUCT_REVENUE, 
    PRODUCT_SKU, 
    PRODUCT_NAME, 
    PRODUCT_RECOMMENDATION_TYPE 
FROM WH.segment.dim_pa_order_items --WH.SEGMENT.DIM_PA_ORDER_ITEMS 

UNION ALL   
SELECT 'PE' AS COUNTRY, 
    ORDER_ITEM_ID, 
    ORDER_ID, 
    POC_ID, 
    RECEIVED_AT, 
    PRODUCT_BRAND, 
    PRODUCT_QUANTITY, 
    PRODUCT_REVENUE, 
    PRODUCT_SKU, 
    PRODUCT_NAME, 
    PRODUCT_RECOMMENDATION_TYPE 
FROM WH.segment.dim_pe_order_items --WH.SEGMENT.DIM_PE_ORDER_ITEMS 

UNION ALL   
SELECT 'PY' AS COUNTRY, 
    ORDER_ITEM_ID, 
    ORDER_ID, 
    POC_ID, 
    RECEIVED_AT, 
    PRODUCT_BRAND, 
    PRODUCT_QUANTITY, 
    PRODUCT_REVENUE, 
    PRODUCT_SKU, 
    PRODUCT_NAME, 
    PRODUCT_RECOMMENDATION_TYPE 
FROM WH.segment.dim_py_order_items 

UNION ALL   
SELECT 'ZA' AS COUNTRY, 
    ORDER_ITEM_ID, 
    ORDER_ID, 
    POC_ID, 
    RECEIVED_AT, 
    PRODUCT_BRAND, 
    PRODUCT_QUANTITY, 
    PRODUCT_REVENUE, 
    PRODUCT_SKU, 
    PRODUCT_NAME, 
    PRODUCT_RECOMMENDATION_TYPE 
FROM WH.segment.dim_za_order_items --WH.SEGMENT.DIM_ZA_ORDER_ITEMS
