-- Data should be updated incrementally - not currently in production
-- Sourced from WH.SEGMENT FACT tables that are based off of SEGMENT_EVENTS.XX.PRODUCT_ADDED

SELECT 'AR' AS COUNTRY,
    PRODUCT_ADDED_ID, 
    POC_ID, 
    USER_ID,  
    BRAND, 
    PRODUCT_SKU, 
    RECEIVED_AT,
    QUANTITY_ADDED,
    RECOMMENDATION_TYPE
FROM WH.segment.fact_ar_product_added --WH.SEGMENT.FACT_AR_PRODUCT_ADDED

UNION ALL
SELECT 'BR' AS COUNTRY,
    PRODUCT_ADDED_ID, 
    POC_ID, 
    USER_ID,  
    BRAND, 
    PRODUCT_SKU, 
    RECEIVED_AT,
    QUANTITY_ADDED,
    RECOMMENDATION_TYPE
FROM WH.segment.fact_br_product_added --WH.SEGMENT.FACT_BR_PRODUCT_ADDED--

UNION ALL
SELECT 'CO' AS COUNTRY,
    PRODUCT_ADDED_ID, 
    POC_ID, 
    USER_ID,  
    BRAND, 
    PRODUCT_SKU, 
    RECEIVED_AT,
    QUANTITY_ADDED,
    RECOMMENDATION_TYPE
FROM WH.segment.fact_co_product_added--WH.SEGMENT.FACT_CO_PRODUCT_ADDED--

UNION ALL
SELECT 'DO' AS COUNTRY,
    PRODUCT_ADDED_ID, 
    POC_ID, 
    USER_ID,  
    BRAND, 
    PRODUCT_SKU, 
    RECEIVED_AT,
    QUANTITY_ADDED,
    RECOMMENDATION_TYPE
FROM WH.segment.fact_do_product_added--WH.SEGMENT.FACT_DO_PRODUCT_ADDED--

UNION ALL
SELECT 'EC' AS COUNTRY,
    PRODUCT_ADDED_ID, 
    POC_ID, 
    USER_ID,  
    BRAND, 
    PRODUCT_SKU, 
    RECEIVED_AT,
    QUANTITY_ADDED,
    RECOMMENDATION_TYPE
FROM WH.segment.fact_ec_product_added--WH.SEGMENT.FACT_EC_PRODUCT_ADDED--

UNION ALL
SELECT 'MX' AS COUNTRY,
    PRODUCT_ADDED_ID, 
    POC_ID, 
    USER_ID,  
    BRAND, 
    PRODUCT_SKU, 
    RECEIVED_AT,
    QUANTITY_ADDED,
    RECOMMENDATION_TYPE
FROM WH.segment.fact_mx_product_added--WH.SEGMENT.FACT_MX_PRODUCT_ADDED--

UNION ALL
SELECT 'PA' AS COUNTRY,
    PRODUCT_ADDED_ID, 
    POC_ID, 
    USER_ID,  
    BRAND, 
    PRODUCT_SKU, 
    RECEIVED_AT,
    QUANTITY_ADDED,
    RECOMMENDATION_TYPE
FROM WH.segment.fact_pa_product_added--WH.SEGMENT.FACT_PA_PRODUCT_ADDED--

UNION ALL
SELECT 'PE' AS COUNTRY,
    PRODUCT_ADDED_ID, 
    POC_ID, 
    USER_ID,  
    BRAND, 
    PRODUCT_SKU, 
    RECEIVED_AT,
    QUANTITY_ADDED,
    RECOMMENDATION_TYPE
FROM WH.segment.fact_pe_product_added--WH.SEGMENT.FACT_PA_PRODUCT_ADDED--

UNION ALL
SELECT 'PY' AS COUNTRY,
    PRODUCT_ADDED_ID, 
    POC_ID, 
    USER_ID,  
    BRAND, 
    PRODUCT_SKU, 
    RECEIVED_AT,
    QUANTITY_ADDED,
    RECOMMENDATION_TYPE
FROM WH.segment.fact_py_product_added--WH.SEGMENT.FACT_PY_PRODUCT_ADDED--

UNION ALL
SELECT 'ZA' AS COUNTRY,
    PRODUCT_ADDED_ID, 
    POC_ID, 
    USER_ID,  
    BRAND, 
    PRODUCT_SKU, 
    RECEIVED_AT,
    QUANTITY_ADDED,
    RECOMMENDATION_TYPE
FROM WH.segment.fact_za_product_added--WH.SEGMENT.FACT_ZA_PRODUCT_ADDED--
