SELECT COUNTRY,
    DATE_TRUNC('MONTH', SENT_AT) AS MONTH,
    COUNT(DISTINCT POC_ID) AS ACTIVE_POCS,
    SUM(N_IN_APP_MESSAGES) AS TOTAL_IN_APP_MESSAGES,
    SUM(N_PUSH_MESSAGES) AS TOTAL_PUSH_MESSAGES,
    SUM(TOTAL_MESSAGES) AS N_TOTAL_MESSAGES,
    TOTAL_IN_APP_MESSAGES + TOTAL_PUSH_MESSAGES AS SUM_TOTAL_MESSAGES,
    N_TOTAL_MESSAGES / ACTIVE_POCS AS FREQUENCY,
    SUM(SALES_MESSAGES) AS TOTAL_SALES_MESSAGES,
    TOTAL_SALES_MESSAGES / ACTIVE_POCS AS SALES_FREQUENCY,
    SUM(REWARDS_MESSAGES) AS TOTAL_REWARDS_MESSAGES,
    TOTAL_REWARDS_MESSAGES / ACTIVE_POCS AS REWARDS_FREQUENCY,
    SUM(MARKETPLACE_MESSAGES) AS TOTAL_MARKETPLACE_MESSAGES,
    TOTAL_MARKETPLACE_MESSAGES / ACTIVE_POCS AS MARKETPLACE_FREQUENCY,
    SUM(ALGO_MESSAGES) AS TOTAL_ALGO_MESSAGES,
    TOTAL_ALGO_MESSAGES / ACTIVE_POCS AS ALGO_FREQUENCY,
    SUM(COMMERCIAL_MESSAGES) AS TOTAL_COMMERCIAL_MESSAGES,
    TOTAL_COMMERCIAL_MESSAGES / ACTIVE_POCS AS COMMERCIAL_FREQUENCY,
    SUM(N_ORDER_VIS_MESSAGES) AS TOTAL_ORDER_VIS_MESSAGES,
    TOTAL_ORDER_VIS_MESSAGES / ACTIVE_POCS AS ORDER_VIS_FREQUENCY
FROM WH.DATAMARTS_DIGITAL_COMMS.DIM_POC_MESSAGE_FREQUENCY
WHERE MONTH IS NOT NULL
GROUP BY COUNTRY, MONTH
