WITH RL30D AS (
SELECT COUNTRY,
    COUNT(DISTINCT USER_ID) AS USERS_REACHED,
    COUNT(DISTINCT POC_ID) AS POCS_REACHED
FROM WH.DATAMARTS_DIGITAL_COMMS.FACT_GLOBAL_MESSAGE_SENDS
WHERE DATE_TRUNC('DAY', RECEIVED_AT) BETWEEN CURRENT_DATE -31 AND CURRENT_DATE -1
GROUP BY COUNTRY
),

MOBILE_USERS AS (
SELECT COUNTRY,
    COUNT(DISTINCT USER_ID) AS MOBILE_USERS
FROM WH.DATAMARTS_DIGITAL_COMMS.DIM_USERS_W_PLATFORM
WHERE PLATFORM IN ('android', 'ios')
GROUP BY COUNTRY
),

MOBILE_POCS AS (
SELECT COUNTRY,
    COUNT(DISTINCT POC_ID) AS MOBILE_POCS
FROM WH.DATAMARTS_DIGITAL_COMMS.DIM_POCS_W_PLATFORM
WHERE PLATFORM IN ('android', 'ios')
GROUP BY COUNTRY
)

SELECT R.COUNTRY,
    R.USERS_REACHED,
    U.MOBILE_USERS,
    R.POCS_REACHED,
    P.MOBILE_POCS
FROM RL30D AS R
LEFT JOIN MOBILE_USERS U
    ON R.COUNTRY = U.COUNTRY
LEFT JOIN MOBILE_POCS P
    ON R.COUNTRY = P.COUNTRY
