WITH SENDS AS (
SELECT COUNTRY,
    DATE_TRUNC('DAY', RECEIVED_AT) AS DAY,
    CAMPAIGN_TYPE,
    CHANNEL,
    COUNT(DISTINCT MESSAGE_ID) AS SENDS
FROM WH.DATAMARTS_DIGITAL_COMMS.FACT_GLOBAL_MESSAGE_SENDS
GROUP BY COUNTRY,
  DAY,
  CAMPAIGN_TYPE,
  CHANNEL
),
CLICKS AS (
SELECT COUNTRY,
    DATE_TRUNC('DAY', RECEIVED_AT) AS DAY,
    CAMPAIGN_TYPE,
    CHANNEL,
    COUNT(DISTINCT MESSAGE_ID) AS CLICKS
FROM WH.DATAMARTS_DIGITAL_COMMS.FACT_GLOBAL_MESSAGE_CLICKS
GROUP BY COUNTRY,
  DAY,
  CAMPAIGN_TYPE,
  CHANNEL
)
SELECT COALESCE(S.COUNTRY, C.COUNTRY) AS COUNTRY,
    COALESCE(S.DAY, C.DAY) AS DATE,
    COALESCE(S.CHANNEL, C.CHANNEL) AS CHANNEL,
    COALESCE(S.CAMPAIGN_TYPE, C.CAMPAIGN_TYPE) AS CAMPAIGN_TYPE,
    IFNULL(SENDS, 0) AS "SENDS", 
    IFNULL(CLICKS, 0) AS "CLICKS",
    IFNULL(DIV0("CLICKS", SENDS), 0) AS CTR
FROM SENDS S
FULL OUTER JOIN CLICKS C
    ON S.COUNTRY = C.COUNTRY
    AND S.DAY = C.DAY
    AND S.CHANNEL = C.CHANNEL
    AND S.CAMPAIGN_TYPE = C.CAMPAIGN_TYPE
