-- Market Dash Sends/Clicks
WITH CAMPAIGNS AS (
SELECT SD.COUNTRY,
    DAY,
    CHANNEL,
    SD.CAMPAIGN_ID,
    M.CAMPAIGN_TYPE,
    SENDS,
    CLICKS,
    DIV0(CLICKS, SENDS) AS CTR
FROM WH.DM_DIGITAL_COMMS.CAMPAIGN_COMMS_STATISTICS_DAILY SD
LEFT JOIN WH.DM_DIGITAL_COMMS.GLOBAL_CAMPAIGN_METADATA M
    ON SD.COUNTRY = M.COUNTRY
    AND SD.CAMPAIGN_ID = M.CAMPAIGN_ID
)
SELECT COUNTRY,
    DATE,
    CHANNEL,
    CAMPAIGN_TYPE,
    SUM(SENDS) AS SENDS,
    SUM(CLICKS) AS CLICKS,
    DIV0(TOTAL_CLICKS, TOTAL_SENDS) AS CTR
FROM CAMPAIGNS
WHERE DAY IS NOT NULL
GROUP BY COUNTRY,
    DAY,
    CHANNEL,
    CAMPAIGN_TYPE
