WITH SENDS AS (
SELECT COUNTRY,
    DATE_TRUNC('DAY', RECEIVED_AT) AS DAY,
    CAMPAIGN_ID,
    CAMPAIGN_NAME,
    CHANNEL,
    CAMPAIGN_TYPE,
    CAMPAIGN_SUBTYPE,
    COUNT(MESSAGE_ID) AS SENDS
FROM WH.DATAMARTS_DIGITAL_COMMS.FACT_GLOBAL_MESSAGE_SENDS
GROUP BY COUNTRY,
  DAY,
  CAMPAIGN_ID,
  CAMPAIGN_NAME,
  CHANNEL,
  CAMPAIGN_TYPE,
  CAMPAIGN_SUBTYPE
),
CLICKS AS (
SELECT COUNTRY,
    DATE_TRUNC('DAY', RECEIVED_AT) AS DAY,
    CAMPAIGN_ID,
    CAMPAIGN_NAME,
    CHANNEL,
    CAMPAIGN_TYPE,
    CAMPAIGN_SUBTYPE,
    COUNT(MESSAGE_ID) AS CLICKS
FROM WH.DATAMARTS_DIGITAL_COMMS.FACT_GLOBAL_MESSAGE_CLICKS
GROUP BY COUNTRY,
  DAY,
  CAMPAIGN_ID,
  CAMPAIGN_NAME,
  CHANNEL,
  CAMPAIGN_TYPE,
  CAMPAIGN_SUBTYPE
)
SELECT S.COUNTRY,
    S.DAY,
    S.CAMPAIGN_ID,
    S.CAMPAIGN_NAME,
    S.CHANNEL,
    S.CAMPAIGN_TYPE,
    S.CAMPAIGN_SUBTYPE,
    SENDS,
    IFNULL(CLICKS, 0) AS "CLICKS",
    IFNULL(DIV0("CLICKS", SENDS), 0) AS CTR
FROM SENDS S
LEFT JOIN CLICKS C
    ON S.COUNTRY = C.COUNTRY
    AND S.DAY = C.DAY
    AND S.CAMPAIGN_ID = C.CAMPAIGN_ID
    AND S.CAMPAIGN_NAME = C.CAMPAIGN_NAME
    AND S.CHANNEL = C.CHANNEL
    AND S.CAMPAIGN_TYPE = C.CAMPAIGN_TYPE
    AND S.CAMPAIGN_SUBTYPE = C.CAMPAIGN_SUBTYPE
WHERE S.CAMPAIGN_ID IS NOT NULL
