--This table contains aggregated campaign stats
--The current version joins to the campaign conversion tables
--The future version will not contain this info
--and will join to a separate conversion table when needed
WITH CAMPAIGN_SENDS AS (
SELECT COUNTRY,
    CAMPAIGN_ID,
    CHANNEL,
    COUNT(DISTINCT USER_ID) AS REACH_USERS,
    COUNT(DISTINCT POC_ID) AS REACH_POCS,
    COUNT(ID) AS SENDS
FROM {{ ref('tracks_global_messages' )}}
WHERE EVENT IN ('in_app_message_viewed', 'push_notification_sent')
GROUP BY COUNTRY,
  CAMPAIGN_ID,
  CHANNEL
),

CAMPAIGN_CLICKS AS (
SELECT COUNTRY,
    CAMPAIGN_ID,
    CHANNEL,
    COUNT(DISTINCT USER_ID) AS CLICK_USERS,
    COUNT(DISTINCT POC_ID) AS CLICK_POCS,
    COUNT(ID) AS CLICKS
FROM {{ ref('tracks_global_messages' )}}
WHERE EVENT IN ('in_app_message_clicked', 'push_notification_tapped')
GROUP BY COUNTRY,
  CAMPAIGN_ID,
  CHANNEL
),

CAMPAIGN_TTC AS (
SELECT COUNTRY,
    CAMPAIGN_ID,
    CHANNEL,
    AVG(SECONDS_DIFF) AS AVG_SECONDS_TO_CLICK
FROM {{ ref('background_time_to_click_events' )}}
GROUP BY COUNTRY,
    CAMPAIGN_ID,
    CHANNEL
),

CONV AS (
SELECT COUNTRY,
  CAMPAIGN_ID,
  CHANNEL,
  CONVERSION_TYPE,
  POCS_CONVERTED,
  USERS_CONVERTED,
  CONVERSIONS
FROM {{ ref('campaign_conversion_algo' )}}

UNION ALL
SELECT COUNTRY,
  CAMPAIGN_ID,
  CHANNEL,
  CONVERSION_TYPE,
  POCS_CONVERTED,
  USERS_CONVERTED,
  CONVERSIONS
FROM {{ ref('campaign_conversion_photo_challenge' )}}

UNION ALL
SELECT COUNTRY,
  CAMPAIGN_ID,
  CHANNEL,
  CONVERSION_TYPE,
  POCS_CONVERTED,
  USERS_CONVERTED,
  CONVERSIONS
FROM {{ ref('campaign_conversion_purchase_challenge' )}}

UNION ALL
SELECT COUNTRY,
  CAMPAIGN_ID,
  CHANNEL,
  CONVERSION_TYPE,
  POCS_CONVERTED,
  USERS_CONVERTED,
  CONVERSIONS
FROM {{ ref('campaign_conversion_redemption' )}}

UNION ALL
SELECT COUNTRY,
  CAMPAIGN_ID,
  CHANNEL,
  CONVERSION_TYPE,
  POCS_CONVERTED,
  USERS_CONVERTED,
  CONVERSIONS
FROM {{ ref('campaign_conversion_sales' )}}
)

SELECT M.COUNTRY,
    M.CAMPAIGN_ID,
    S.CHANNEL,
    IFNULL(REACH_USERS, '0') AS REACH_USERS,
    IFNULL(REACH_POCS, '0') AS REACH_POCS,
    IFNULL(CLICK_USERS, '0') AS CLICK_USERS,
    IFNULL(CLICK_POCS, '0') AS CLICK_POCS,
    IFNULL(SENDS, '0') AS SENDS,
    IFNULL(CLICKS, '0') AS CLICKS,
    IFNULL(AVG_SECONDS_TO_CLICK, '0') AS AVG_SECONDS_TO_CLICK,
    CONVERSION_TYPE,
    IFNULL(POCS_CONVERTED, 0) AS POCS_CONVERTED,
    IFNULL(USERS_CONVERTED, 0) AS USERS_CONVERTED,
    IFNULL(CONVERSIONS, 0) AS CONVERSIONS
FROM {{ ref('global_campaign_metadata' )}} M
LEFT JOIN CAMPAIGN_SENDS S
    ON M.COUNTRY = S.COUNTRY
    AND M.CAMPAIGN_ID = S.CAMPAIGN_ID
LEFT JOIN CAMPAIGN_CLICKS C
    ON M.COUNTRY = C.COUNTRY
    AND M.CAMPAIGN_ID = C.CAMPAIGN_ID
    AND S.CHANNEL = C.CHANNEL
LEFT JOIN CAMPAIGN_TTC TTC
    ON M.COUNTRY = TTC.COUNTRY
    AND M.CAMPAIGN_ID = TTC.CAMPAIGN_ID
    AND S.CHANNEL = TTC.CHANNEL
LEFT JOIN CONV
    ON M.COUNTRY = CONV.COUNTRY
    AND M.CAMPAIGN_ID = CONV.CAMPAIGN_ID
    AND S.CHANNEL = CONV.CHANNEL
