--Count the number of users per platform by month
WITH MONTHLY_MOBILE_USERS AS (
SELECT COUNTRY,
  MONTH,
  PLATFORM,
  COUNT(DISTINCT USER_ID) AS MOBILE_USERS
FROM WH.DATAMARTS_DIGITAL_COMMS.DIM_USERS_W_PLATFORM_MONTHLY
WHERE PLATFORM IN ('android', 'ios')
GROUP BY COUNTRY,
  MONTH,
  PLATFORM
),
MONTHLY_PUSH_USERS AS (
SELECT B.COUNTRY,
  DATEADD(MONTH, 1, B.MONTH) AS NEW_MONTH,
  P.PLATFORM,
  COUNT(DISTINCT B.USER_ID) AS PUSH_USERS
FROM WH.DATAMARTS_DIGITAL_COMMS.DIM_MONTHLY_BRAZE_USERS B
JOIN WH.DATAMARTS_DIGITAL_COMMS.DIM_USERS_W_PLATFORM_MONTHLY P
  ON B.COUNTRY = P.COUNTRY
  AND B.MONTH = P.MONTH
  AND B.USER_ID = P.USER_ID
WHERE PLATFORM IN ('android', 'ios')
  AND CHANNEL = 'PUSH'
GROUP BY B.COUNTRY,
  NEW_MONTH,
  P.PLATFORM
)
SELECT M.COUNTRY,
    M.MONTH,
    M.PLATFORM,
    MOBILE_USERS,
    IFNULL(PUSH_USERS, 0) AS PUSH_USERS
FROM MONTHLY_MOBILE_USERS M
LEFT JOIN MONTHLY_PUSH_USERS P
    ON M.COUNTRY = P.COUNTRY
    AND M.MONTH = P.NEW_MONTH
    AND M.PLATFORM = P.PLATFORM
