-- INCLUDE PRODUCT ADDED EVENTS FOR SALES CONVERSION EVENTS
-- USE AN INCREMENTAL LOAD STRATEGY TO REDUCE REFRESH TIMES

SELECT 'AR' AS COUNTRY,
    PRODUCT_ADDED_ID, 
    POC_ID, 
    USER_ID,  
    BRAND, 
    PRODUCT_SKU, 
    RECEIVED_AT,
    QUANTITY_ADDED,
    RECOMMENDATION_TYPE
FROM {{ ref('fact_ar_product_added' )}}

UNION ALL
...
--ALL COUNTRIES
...
