{{
    config(
	incremental_strategy='delete+insert',
        unique_key='ID'
    )
}}
WITH 
{% if adapter.get_relation(this.database, this.schema, this.table) and not flags.FULL_REFRESH %}
T_MAX_DATA AS (select dateadd(HOUR, -6, max(RECEIVED_AT)) AS MAX_DATA from {{ this }}), 
{% else %}
    T_MAX_DATA AS (select to_date('2018-01-01') AS MAX_DATA),
{% endif %} 
MESSAGES AS (
SELECT 'BR' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_BR.EMAIL_BOUNCED

UNION ALL
SELECT 'BR' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_BR.EMAIL_DELIVERED

UNION ALL
SELECT 'BR' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_BR.EMAIL_LINK_CLICKED

UNION ALL
SELECT 'BR' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_BR.EMAIL_MARKED_AS_SPAM

UNION ALL
SELECT 'BR' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_BR.EMAIL_OPENED

UNION ALL
SELECT 'BR' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_BR.EMAIL_SENT

UNION ALL
SELECT 'BR' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_BR.EMAIL_SOFT_BOUNCED

--CO
UNION ALL
SELECT 'CO' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_CO.EMAIL_BOUNCED

UNION ALL
SELECT 'CO' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_CO.EMAIL_DELIVERED

UNION ALL
SELECT 'CO' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_CO.EMAIL_LINK_CLICKED

UNION ALL
SELECT 'CO' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_CO.EMAIL_MARKED_AS_SPAM

UNION ALL
SELECT 'CO' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_CO.EMAIL_OPENED

UNION ALL
SELECT 'CO' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_CO.EMAIL_SENT

UNION ALL
SELECT 'CO' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_CO.EMAIL_SOFT_BOUNCED

--DO
UNION ALL
SELECT 'DO' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE.EMAIL_BOUNCED

UNION ALL
SELECT 'DO' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE.EMAIL_DELIVERED

UNION ALL
SELECT 'DO' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE.EMAIL_LINK_CLICKED

-- //UNION ALL
-- //SELECT 'DO' AS COUNTRY,
-- //    'EMAIL' AS CHANNEL,
-- //    EVENT,
-- //    ID,
-- //    CAMPAIGN_NAME,
-- //    CAMPAIGN_ID,
-- //    USER_ID,
-- //    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
-- //    CONTEXT_TRAITS_EMAIL,
-- //    RECEIVED_AT,
-- //    SENT_AT,
-- //    TIMESTAMP,
-- //    CURRENT_TIMESTAMP AS UPLOADED_AT
-- //FROM SEGMENT_EVENTS.BRAZE.EMAIL_MARKED_AS_SPAM

UNION ALL
SELECT 'DO' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE.EMAIL_OPENED

UNION ALL
SELECT 'DO' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE.EMAIL_SENT

UNION ALL
SELECT 'DO' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE.EMAIL_SOFT_BOUNCED

-- EC
-- UNION ALL
-- SELECT 'EC' AS COUNTRY,
--     'EMAIL' AS CHANNEL,
--     EVENT,
--     ID,
--     CAMPAIGN_NAME,
--     CAMPAIGN_ID,
--     USER_ID,
--     SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
--     CONTEXT_TRAITS_EMAIL,
--     RECEIVED_AT,
--     SENT_AT,
--     TIMESTAMP,
--     CURRENT_TIMESTAMP AS UPLOADED_AT
-- FROM SEGMENT_EVENTS.BRAZE_EC.EMAIL_BOUNCED

UNION ALL
SELECT 'EC' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_EC.EMAIL_DELIVERED

UNION ALL
SELECT 'EC' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_EC.EMAIL_LINK_CLICKED

-- //UNION ALL
-- //SELECT 'EC' AS COUNTRY,
-- //    'EMAIL' AS CHANNEL,
-- //    EVENT,
-- //    ID,
-- //    CAMPAIGN_NAME,
-- //    CAMPAIGN_ID,
-- //    USER_ID,
-- //    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
-- //    CONTEXT_TRAITS_EMAIL,
-- //    RECEIVED_AT,
-- //    SENT_AT,
-- //    TIMESTAMP,
-- //    CURRENT_TIMESTAMP AS UPLOADED_AT
-- //FROM SEGMENT_EVENTS.BRAZE_EC.EMAIL_MARKED_AS_SPAM

UNION ALL
SELECT 'EC' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_EC.EMAIL_OPENED

UNION ALL
SELECT 'EC' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_EC.EMAIL_SENT

-- UNION ALL
-- SELECT 'EC' AS COUNTRY,
--     'EMAIL' AS CHANNEL,
--     EVENT,
--     ID,
--     CAMPAIGN_NAME,
--     CAMPAIGN_ID,
--     USER_ID,
--     SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
--     CONTEXT_TRAITS_EMAIL,
--     RECEIVED_AT,
--     SENT_AT,
--     TIMESTAMP,
--     CURRENT_TIMESTAMP AS UPLOADED_AT
-- FROM SEGMENT_EVENTS.BRAZE_EC.EMAIL_SOFT_BOUNCED

-- MX
UNION ALL
SELECT 'MX' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_MX.EMAIL_BOUNCED

UNION ALL
SELECT 'MX' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_MX.EMAIL_DELIVERED

UNION ALL
SELECT 'MX' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_MX.EMAIL_LINK_CLICKED

-- //UNION ALL
-- //SELECT 'MX' AS COUNTRY,
-- //    'EMAIL' AS CHANNEL,
-- //    EVENT,
-- //    ID,
-- //    CAMPAIGN_NAME,
-- //    CAMPAIGN_ID,
-- //    USER_ID,
-- //    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
-- //    CONTEXT_TRAITS_EMAIL,
-- //    RECEIVED_AT,
-- //    SENT_AT,
-- //    TIMESTAMP,
-- //    CURRENT_TIMESTAMP AS UPLOADED_AT
-- //FROM SEGMENT_EVENTS.BRAZE_MX.EMAIL_MARKED_AS_SPAM

UNION ALL
SELECT 'MX' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_MX.EMAIL_OPENED

UNION ALL
SELECT 'MX' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_MX.EMAIL_SENT

UNION ALL
SELECT 'MX' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_MX.EMAIL_SOFT_BOUNCED

-- PE
UNION ALL
SELECT 'PE' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_PE.EMAIL_BOUNCED

UNION ALL
SELECT 'PE' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_PE.EMAIL_DELIVERED

UNION ALL
SELECT 'PE' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_PE.EMAIL_LINK_CLICKED

-- //UNION ALL
-- //SELECT 'PE' AS COUNTRY,
-- //    'EMAIL' AS CHANNEL,
-- //    EVENT,
-- //    ID,
-- //    CAMPAIGN_NAME,
-- //    CAMPAIGN_ID,
-- //    USER_ID,
-- //    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
-- //    CONTEXT_TRAITS_EMAIL,
-- //    RECEIVED_AT,
-- //    SENT_AT,
-- //    TIMESTAMP,
-- //    CURRENT_TIMESTAMP AS UPLOADED_AT
-- //FROM SEGMENT_EVENTS.BRAZE_PE.EMAIL_MARKED_AS_SPAM

UNION ALL
SELECT 'PE' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_PE.EMAIL_OPENED

UNION ALL
SELECT 'PE' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_PE.EMAIL_SENT

UNION ALL
SELECT 'PE' AS COUNTRY,
    'EMAIL' AS CHANNEL,
    EVENT,
    ID,
    CAMPAIGN_NAME,
    CAMPAIGN_ID,
    USER_ID,
    SPLIT_PART(USER_ID, '_', 1) AS POC_ID,
    CONTEXT_TRAITS_EMAIL,
    RECEIVED_AT,
    SENT_AT,
    TIMESTAMP,
    CURRENT_TIMESTAMP AS UPLOADED_AT
FROM SEGMENT_EVENTS.BRAZE_PE.EMAIL_SOFT_BOUNCED
)

SELECT *
FROM MESSAGES
{% if adapter.get_relation(this.database, this.schema, this.table) and not flags.FULL_REFRESH %}
--WHERE a.RECEIVED_AT > (select max(RECEIVED_AT) from {{ this }})
       WHERE RECEIVED_AT > (select MAX_DATA from T_MAX_DATA)
{% endif %}
