
WITH
IMPRESSIONS AS (
SELECT *
FROM {{ ref('tracks_global_messages' )}}
)

SELECT S.COUNTRY,
  USER_ID,
  DATE_TRUNC('DAY', RECEIVED_AT) AS DAY,
  SUM(CASE WHEN CHANNEL = 'PUSH' THEN 1 ELSE 0 END) AS PUSH_IMPRESSIONS,
  SUM(CASE WHEN CHANNEL = 'IN-APP' THEN 1 ELSE 0 END) AS IN_APP_IMPRESSIONS,
  COUNT(ID) AS TOTAL_IMPRESSIONS,
  --Sales
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Sales' AND CHANNEL = 'IN-APP' THEN 1 ELSE 0 END) AS IN_APP_SALES_IMPRESSIONS,
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Sales' AND CHANNEL = 'PUSH' THEN 1 ELSE 0 END) AS PUSH_SALES_IMPRESSIONS,
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Sales' THEN 1 ELSE 0 END) AS SALES_IMPRESSIONS,
  --Algo
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Algo' AND CHANNEL = 'IN-APP' THEN 1 ELSE 0 END) AS IN_APP_ALGO_IMPRESSIONS,
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Algo' AND CHANNEL = 'PUSH' THEN 1 ELSE 0 END) AS PUSH_ALGO_IMPRESSIONS,
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Algo' THEN 1 ELSE 0 END) AS ALGO_IMPRESSIONS,
  --Rewards
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Rewards' AND CHANNEL = 'IN-APP' AND CAMPAIGN_SUBTYPE = 'Photo Challenge' THEN 1 ELSE 0 END) AS IN_APP_REWARDS_PHOTO_IMPRESSIONS,
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Rewards' AND CHANNEL = 'PUSH' AND CAMPAIGN_SUBTYPE = 'Photo Challenge' THEN 1 ELSE 0 END) AS PUSH_REWARDS_PHOTO_IMPRESSIONS,
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Rewards' AND CAMPAIGN_SUBTYPE = 'Photo Challenge' THEN 1 ELSE 0 END) AS REWARDS_PHOTO_IMPRESSIONS,
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Rewards' AND CHANNEL = 'IN-APP' AND CAMPAIGN_SUBTYPE = 'Purchase Challenge' THEN 1 ELSE 0 END) AS IN_APP_REWARDS_PURCHASE_IMPRESSIONS,
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Rewards' AND CHANNEL = 'PUSH' AND CAMPAIGN_SUBTYPE = 'Purchase Challenge' THEN 1 ELSE 0 END) AS PUSH_REWARDS_PURCHASE_IMPRESSIONS,
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Rewards' AND CAMPAIGN_SUBTYPE = 'Purchase Challenge' THEN 1 ELSE 0 END) AS REWARDS_PURCHASE_IMPRESSIONS,
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Rewards' AND CHANNEL = 'IN-APP' AND CAMPAIGN_SUBTYPE = 'Redemption' THEN 1 ELSE 0 END) AS IN_APP_REWARDS_REDEMPTION_IMPRESSIONS,
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Rewards' AND CHANNEL = 'PUSH' AND CAMPAIGN_SUBTYPE = 'Redemption' THEN 1 ELSE 0 END) AS PUSH_REWARDS_REDEMPTION_IMPRESSIONS,
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Rewards' AND CAMPAIGN_SUBTYPE = 'Redemption' THEN 1 ELSE 0 END) AS REWARDS_REDEMPTION_IMPRESSIONS,
  --Marketplace
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Marketplace' AND CHANNEL = 'IN-APP' THEN 1 ELSE 0 END) AS IN_APP_MARKETPLACE_IMPRESSIONS,
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Marketplace' AND CHANNEL = 'PUSH' THEN 1 ELSE 0 END) AS PUSH_MARKETPLACE_IMPRESSIONS,
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Marketplace' THEN 1 ELSE 0 END) AS MARKETPLACE_IMPRESSIONS,
  --Satisfaction
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Satisfaction' AND CHANNEL = 'IN-APP' THEN 1 ELSE 0 END) AS IN_APP_SATISFACTION_IMPRESSIONS,
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Satisfaction' AND CHANNEL = 'PUSH' THEN 1 ELSE 0 END) AS PUSH_SATISFACTION_IMPRESSIONS,
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Satisfaction' THEN 1 ELSE 0 END) AS SATISFACTION_IMPRESSIONS,
  --Survey
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Survey' AND CHANNEL = 'IN-APP' THEN 1 ELSE 0 END) AS IN_APP_SURVEY_IMPRESSIONS,
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Survey' AND CHANNEL = 'PUSH' THEN 1 ELSE 0 END) AS PUSH_SURVEY_IMPRESSIONS,
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Survey' THEN 1 ELSE 0 END) AS SURVEY_IMPRESSIONS,
  --Logistics
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Logistics' AND CAMPAIGN_SUBTYPE != 'Order Visibility' AND CHANNEL = 'IN-APP' THEN 1 ELSE 0 END) AS IN_APP_LOGISTICS_IMPRESSIONS,
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Logistics' AND CAMPAIGN_SUBTYPE != 'Order Visibility' AND CHANNEL = 'PUSH' THEN 1 ELSE 0 END) AS PUSH_LOGISTICS_IMPRESSIONS,
  SUM(CASE WHEN CAMPAIGN_TYPE = 'Logistics' AND CAMPAIGN_SUBTYPE != 'Order Visibility' THEN 1 ELSE 0 END) AS LOGISTICS_IMPRESSIONS,
  --Order Viz
  SUM(CASE WHEN CAMPAIGN_SUBTYPE = 'Order Visibility' THEN 1 ELSE 0 END) AS ORDER_VIS_IMPRESSIONS,
  SUM(CASE WHEN CAMPAIGN_SUBTYPE = 'Order Visibility' AND CHANNEL = 'IN-APP' THEN 1 ELSE 0 END) AS IN_APP_ORDER_VIS_IMPRESSIONS,
  SUM(CASE WHEN CAMPAIGN_SUBTYPE = 'Order Visibility' AND CHANNEL = 'PUSH' THEN 1 ELSE 0 END) AS PUSH_ORDER_VIS_IMPRESSIONS,
  CONCAT(S.COUNTRY, '-', USER_ID, '-', DAY) AS UID,
  CURRENT_TIMESTAMP AS LOADED_AT
FROM IMPRESSIONS S
LEFT JOIN {{ ref('global_campaign_metadata' )}} M
    ON S.COUNTRY = M.COUNTRY
    AND S.CAMPAIGN_ID = M.CAMPAIGN_ID
WHERE EVENT IN ('in_app_message_viewed', 'push_notification_sent')
GROUP BY S.COUNTRY, USER_ID, DAY
