WITH STG AS (
SELECT COUNTRY,
    USER_ID,
    DATE_TRUNC('DAY', CLICK_TIME) AS DAY,
    CHANNEL,
    AVG(SECONDS_DIFF) AS AVG_PUSH_SECONDS_TO_CLICK
FROM {{ ref('background_time_to_click_events' )}}
GROUP BY COUNTRY,
    USER_ID,
    DAY,
    CHANNEL
)

SELECT COUNTRY, 
    USER_ID,
    DAY,
    CHANNEL,
    AVG_PUSH_SECONDS_TO_CLICK,
    CONCAT(COUNTRY, '-', USER_ID, '-', DAY) AS UID,
    CURRENT_TIMESTAMP AS LOADED_AT
FROM STG
WHERE CHANNEL = 'PUSH'
